approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^No'
reject_value: -1
reset_on_push: true
author_approval: ignored
reviewers:
  required: 1
  members:
    - prologic
    - nathschmidt
    - Osso
    - spaceone
