language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
script: python setup.py test
after_success:
  - coveralls
